apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: app-of-apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: signal
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: '0.8.3'
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    namespace: app-of-apps-external-secrets
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true